---
- name: Reboot the server
  hosts: all  # This targets all hosts in your inventory 
  become: true
  tasks:

      - name: Reboot the remote server
        tags: reboot
        become: true
        become_user: root
        shell: "sleep 5 && reboot"
        async: 1
        poll: 0

      - name: Waiting for reboot to complete
        wait_for_connection:
          connect_timeout: 10
          sleep: 5
          delay: 5
          timeout: 300

      - name: Printing the uptime of servers
        shell: "uptime"
        register: Uptime

      - debug: var=Uptime
