- name: Check if reboot required
  become: true
  become_user: root 
  stat:
    path: /var/run/reboot-required
  register: reboot_required_file

- name: Reboot if required
  become: true
  become_user: root 
  reboot:
  when: reboot_required_file.stat.exists == true