---
- hosts: all

  become: true
  become_user: root
  tasks:
    - name: update apt packages
      apt:
        upgrade: yes
        update_cache: yes
      register: apt_action
      retries: 100
      until: apt_action is success or ('Failed to lock apt for exclusive operation' not in apt_action.msg and '/var/lib/dpkg/lock' not in apt_action.msg)
